export const GET_LESSONS = 'GET_LESSONS';
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS';
export const CLEAR_LESSONS = 'CLEAR_LESSONS';
export const SET_SELECTED_LESSON = 'SET_SELECTED_LESSON';